owner: endeavour-predict
repo: endeavour-predict-upptime

sites:
  - name: Endeavour Predict Developer Portal
    url: https://endeavour-predict-apim.developer.azure-api.net
  - name: Endeavour Predict API Gateway
    url: https://endeavour-predict-apim.azure-api.net

status-website:
  baseUrl: /endeavour-predict-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Endeavour Predict Service Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Service Status for the Endeavour Predict suite of services.
